---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-simulator
  namespace: gdc-pm
  labels:
    app: telemetry-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-simulator
  template:
    metadata:
      labels:
        app: telemetry-simulator
    spec:
      containers:
        - name: telemetry-simulator
          image: GCR_IMAGE_PLACEHOLDER
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: host
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: port
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
            - name: RABBITMQ_VHOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: vhost
            - name: TELEMETRY_INTERVAL
              value: "5"
            - name: INJECT_FAULT
              value: "none"
            - name: INJECT_ASSET
              value: "COMP-TX-VALLEY-01"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
