#!/bin/bash
# =========================================================================
# Script: setup-workspace.sh  (CANONICAL TEMPLATE)
# Copy to: <project-root>/scripts/setup-workspace.sh
#
# Purpose: Configures VS Code workspace and environment variables for strict
#          project isolation. Prevents concurrent Cline/terminal sessions
#          from modifying global ~/.config/gcloud or ~/.kube/config state.
#
# Usage (one-time per clone, or after adding new workspace):
#   bash scripts/setup-workspace.sh
#
# After running: close and reopen the project folder in VS Code so that
# terminal.integrated.env.linux takes effect in all new terminals.
# =========================================================================

set -e

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="${PROJECT_ROOT}/terraform"
TF_VARS="${TF_DIR}/terraform.tfvars"

echo "🔍 Locating project configuration..."

# 1. Read PROJECT_ID from terraform.tfvars
if [ ! -f "$TF_VARS" ]; then
    echo "❌ Error: $TF_VARS not found."
    echo "   Please create it from terraform.tfvars.example before running this script."
    exit 1
fi

export PROJECT_ID
PROJECT_ID=$(grep 'project_id' "$TF_VARS" | awk -F'"' '{print $2}')

if [ -z "$PROJECT_ID" ]; then
    echo "❌ Error: Could not extract 'project_id' from $TF_VARS"
    exit 1
fi

echo "✅ Found PROJECT_ID: ${PROJECT_ID}"

# 2. Generate .env file
ENV_FILE="${PROJECT_ROOT}/.env"
echo "📝 Generating ${ENV_FILE}..."

cat > "$ENV_FILE" <<EOF
# Workspace Isolation Environment Variables
# Auto-generated by scripts/setup-workspace.sh

# GCP Project Isolation
export GOOGLE_CLOUD_PROJECT=${PROJECT_ID}
export CLOUDSDK_CORE_PROJECT=${PROJECT_ID}

# Kubernetes Context Isolation
export KUBECONFIG=\${PWD}/.kubeconfig

# Internal Script Variables
export PROJECT_ID=${PROJECT_ID}
export KEY_DIR=\${HOME}/gdc-keys/${PROJECT_ID}
EOF

echo "✅ Created .env"

# 3. Generate .vscode/settings.json
VSCODE_DIR="${PROJECT_ROOT}/.vscode"
SETTINGS_FILE="${VSCODE_DIR}/settings.json"

echo "📝 Generating ${SETTINGS_FILE}..."
mkdir -p "$VSCODE_DIR"

if [ -f "$SETTINGS_FILE" ]; then
    if grep -q '"terminal.integrated.env.linux"' "$SETTINGS_FILE"; then
        echo "⚠️  terminal.integrated.env.linux already exists in settings.json. Skipping injection."
    else
        # Insert right after the opening brace
        sed -i.bak -e '1s/{/{/' -e '/^{/a\
    "terminal.integrated.env.linux": {\
        "GOOGLE_CLOUD_PROJECT": "'"${PROJECT_ID}"'",\
        "CLOUDSDK_CORE_PROJECT": "'"${PROJECT_ID}"'",\
        "KUBECONFIG": "${workspaceFolder}/.kubeconfig"\
    },' "$SETTINGS_FILE"
    fi
else
    # Create new settings.json
    cat > "$SETTINGS_FILE" <<EOF
{
    "terminal.integrated.env.linux": {
        "GOOGLE_CLOUD_PROJECT": "${PROJECT_ID}",
        "CLOUDSDK_CORE_PROJECT": "${PROJECT_ID}",
        "KUBECONFIG": "\${workspaceFolder}/.kubeconfig"
    }
}
EOF
fi

echo "✅ Created/Updated .vscode/settings.json"

# 4. Generate .envrc for direnv auto-loading
ENVRC_FILE="${PROJECT_ROOT}/.envrc"
echo "📝 Generating ${ENVRC_FILE}..."

cat > "$ENVRC_FILE" <<'EOF'
# .envrc — direnv workspace isolation
# Reads project_id from terraform/terraform.tfvars and sets all isolation vars.
# Activate with: direnv allow .
PROJECT_ID=$(grep 'project_id' terraform/terraform.tfvars 2>/dev/null | awk -F'"' '{print $2}')
if [ -n "$PROJECT_ID" ]; then
    export GOOGLE_CLOUD_PROJECT=$PROJECT_ID
    export CLOUDSDK_CORE_PROJECT=$PROJECT_ID
    export KUBECONFIG=$PWD/.kubeconfig
    export PROJECT_ID=$PROJECT_ID
    export KEY_DIR=$HOME/gdc-keys/$PROJECT_ID
else
    echo "❌ direnv: terraform/terraform.tfvars not found or missing project_id" >&2
fi
EOF

# Auto-allow if direnv is installed
if command -v direnv &>/dev/null; then
    direnv allow "$PROJECT_ROOT"
    echo "✅ Created .envrc and ran 'direnv allow'"
else
    echo "✅ Created .envrc (install direnv + run 'direnv allow .' to activate)"
fi

echo ""
echo "🎉 Workspace isolation complete!"
echo "   All integrated terminals in this VS Code window will now be sandboxed"
echo "   to use KUBECONFIG and project '${PROJECT_ID}' automatically."
echo ""
echo "⚠️  Important:"
echo "   1. Do NOT run 'gcloud config set project'."
echo "   2. All shell scripts that use gcloud/kubectl/helm/terraform must start with:"
echo "         source ~/scripts/isolation-guard.sh"
echo "   3. Cline ad-hoc commands must be prefixed with: source .env &&"
